name: Nova Bank Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  snyk-security-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install and Authenticate Snyk
        run: |
            npm install snyk -g
            snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test to Catch Vulnerabilities
        run: snyk test || true

      - name: Snyk Open Source to Monitor Project
        run: snyk monitor

        #Test Github Actions Pipeline